export const appModule = [
  { id: '1', label:'设备巡查'},
  { id: '2', label:'消防巡查'},
  { id: '3', label:'维保'},
  { id: '4', label:'设备报修'},
  { id: '5', label:'二次施工'},
  { id: '6', label:'培训考核'},
  { id: '7', label:'可视地图'},
  { id: '20', label:'FAS(仅火警)'},
  { id: '21', label:'FAS'},
  { id: '22', label:'AI火灾识别系统'},
  { id: '41', label:'无线烟感'},
  { id: '42', label:'水位监测'},
  { id: '43', label:'水压监测'},
  { id: '44', label:'水浸监测'},
  { id: '45', label:'电气火灾'},
]
